name: NuGet Generation

on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://nuget.pkg.github.com/FacelessHunter/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}   

      - run: dotnet build
        
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -

      - name: Push generated package to GitHub registry
        run: dotnet nuget push */bin/Release/*.nupkg
